title: R4VDOM
description: "Pentesting Lab & eJPT Notes"
remote_theme: just-the-docs/just-the-docs

# Configuraci√≥n para que se vea modo oscuro (Hacker style)
color_scheme: dark

# Esto permite que GitHub Pages use el tema sin instalar nada
plugins:
  - jekyll-remote-theme
